language: cpp
dist: trusty
os: linux
cache: apt
branches:
  except:
  - ifc
  - lambdas
  - deep-dev-5.0
matrix:
  include:
   - env: BUILD_TYPE=MinSizeRel
     script:
       - docker build --build-arg UBUNTU=xenial --build-arg BUILD_TYPE=$BUILD_TYPE --build-arg TRAVIS=true -t seahorn_xenial_build -f docker/seahorn-full-size-rel.Dockerfile .
       - docker run -v $(pwd):/host -it seahorn_xenial_build /bin/sh -c "cp build/*.tar.gz /host/"
       - |
        if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
          docker build -t seahorn_container -f docker/seahorn.Dockerfile . ;
        else
          docker build --build-arg BASE_IMAGE=seahorn/seahorn-llvm5 -t seahorn_container -f docker/seahorn.Dockerfile . ;
        fi
       - |
        if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
          docker run -v $(pwd):/host -it seahorn_container /bin/sh -c "cd share/seahorn/; lit test" &&
          docker login -u "$DOCKER_USER" -p "$DOCKER_PWD" &&
          docker tag seahorn_container seahorn/seahorn-llvm5:nightly &&
          docker push seahorn/seahorn-llvm5:nightly ;
        else
          docker run -v $(pwd):/host -it seahorn_container /bin/sh -c "cd share/seahorn; lit test" ;
        fi
   - env: BUILD_TYPE=Coverage
     if: type = cron
     script:
       - docker build --build-arg UBUNTU=xenial --build-arg BUILD_TYPE=$BUILD_TYPE --build-arg TRAVIS=true -t seahorn_xenial_build -f docker/seahorn-full-size-rel.Dockerfile .
       - >
         docker run  -v $(pwd):/host -it seahorn_xenial_build /bin/sh -c 
         "bash /seahorn/docker/run_and_collect_cov.sh && mv /seahorn/all.info /host"
         && bash <(curl -s https://codecov.io/bash) -Z -f all.info

services:
  - docker

install: true

notifications:
   slack: seahornteam:NAUqZmZHFFviPH4ktQbJXgKu
   email:
     recipients:
      - seahorn-build@googlegroups.com
     on_success: always
     on_failure: always
